package com.diffblue;

import com.diffblue.ArrayContainsValue;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.rules.ExpectedException;
import org.junit.Test;
import java.lang.reflect.Array;


public class ArrayContainsValueTest {
    @Rule
    public ExpectedException thrown = ExpectedException.none();
    // Test generated by Diffblue Cover.

    @Test
    public void containsInput0ZeroOutputFalse() {

        // Arrange
        final Object[] array = { };
        final Object searchValue = 0;

        // Act
        final boolean retval = ArrayContainsValue.contains(array, searchValue);

        // Assert result
        Assert.assertEquals(false, retval);

    }


    // Test generated by Diffblue Cover.

    @Test
    public void containsInput7ZeroOutputTrue() {

        // Arrange
        final Object[] array = { 0, null, null, null, null, null, null };
        final Object searchValue = 0;

        // Act
        final boolean retval = ArrayContainsValue.contains(array, searchValue);

        // Assert result
        Assert.assertEquals(true, retval);

    }


    // Test generated by Diffblue Cover.

    @Test
    public void containsInput4PositiveOutputTrue() {

        // Arrange
        final Object[] array = { 0, 277_909_921, null, null };
        final Object searchValue = 277_909_921;

        // Act
        final boolean retval = ArrayContainsValue.contains(array, searchValue);

        // Assert result
        Assert.assertEquals(true, retval);

    }

}
